/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'jbe35' at '12/5/16 11:46 AM' with Gradle 3.2.1
 *
 * @author jbe35, @date 12/5/16 11:46 AM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
